export const FETCH_WEATHER_FORECAST_START = 'FETCH_WEATHER_FORECAST_START';
export const FETCH_WEATHER_FORECAST_SUCCESS = 'FETCH_WEATHER_FORECAST_SUCCESS';
export const FETCH_WEATHER_FORECAST_FAILED = 'FETCH_WEATHER_FORECAST_FAILED';
